### ISSUE TITLE
Jest snapshot tests in 3.x-beta version are not deterministic

### ISSUE THREAD

**Issue by diamond-miner** [anastasiia-zolochevska/react-appinsights#42] opened 2019-02-18 11:11 UTC
It appears there is a lack of idempotence as every save generates a new accountAcquisitionDate timestamp which causes the snapshots to not match.

**Comment by pviotti** [comment] 2019-02-20 11:26
Thanks for reporting this. It looks like it may depend on these two lines of code in AppInsights-Js: [Context/User.ts#L114-L115](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/vNext/extensions/applicationinsights-properties-js/src/Context/User.ts#L114-L115), so it may be better to open an issue on that repo and reference this one.  
Can you provide more info or a code snippet to help us reproduce the issue? In particular, what feature were you using (eg `withAITracking`, `setContext`..)?

(Related Jest snapshot testing doc: https://jestjs.io/docs/en/snapshot-testing#2-tests-should-be-deterministic)

**Comment by pviotti** [comment] 2019-04-09 22:24
Closing this as we cannot reproduce this issue anymore with the current version of react-appinsights.

**Closed as completed by pviotti** 2019-04-09 22:24 UTC
Labels: typescript-rewrite
